version: '3'
services:
  # redis:
  #   image: redis
  #   networks:
  #     - webnet

  web:
    image: million-song-challenge
    build: .
    ports:
      - '5000:5000'
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    networks:
      - webnet
    environment:
      DB_URL: postgres://poe:NIEpodam123@db:5432/million-song
      DB_HOST: db # this is available at process.env.DB_HOST in index.js
      DB_USER: poe
      DB_PASSWORD: NIEpodam123
      DB_NAME: million-song
      DB_PORT: 5432
    links:
      - db
    restart: always

  db:
    image: postgres
    networks:
      - webnet
    environment:
      POSTGRES_USER: poe
      POSTGRES_PASSWORD: NIEpodam123
      POSTGRES_DB: million-song
    restart: always

networks:
  webnet:
