version: '3'
services:
  redis:
    image: redis
    networks:
      - webnet
  web:
    image: million-song-challenge
    build: .
    command: node index.js
    ports:
      - '5000:5000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - webnet
    environment:
      DB_HOST: db # this is available at process.env.DB_HOST in index.js
    depends_on:
      - db

  db:
    image: postgres
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: NIEpodam123
      POSTGRES_USER: poe
      POSTGRES_DB: million-song
    ports:
      - '27017:27017'

networks:
  webnet:
